version: '3.7'

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "8080:8080"
      #- "443:443"
      #- "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - SITE_ADDRESS=localhost:8080
volumes:
  caddy_data:
  caddy_config:
