version: '3.7'

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "8080:8080"
      #- "443:443"
      #- "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - SITE_ADDRESS=localhost:8080
    depends_on:
      - keycloak
      - frontend
  keycloak:
    build: ./keycloak/
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_HTTP_RELATIVE_PATH=/auth/
      - KC_PROXY_HEADERS=xforwarded
      - KC_HEALTH_ENABLED=true
    command: start-dev --import-realm
    volumes:
      - ./keycloak/input:/opt/keycloak/data/import:Z
    healthcheck:
      test: /healthcheck
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 10s
  frontend:
    build: ../frontend/
    restart: unless-stopped
    volumes:
      - ../frontend/hivedrive/src/:/usr/local/app/src/:Z
  backend:
    build: ../backend/
    restart: unless-stopped
    depends_on:
      keycloak:
        condition: service_healthy
volumes:
  caddy_data:
  caddy_config:

