name: Docker Compose Actions Workflow

on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3.3.0
      #- run: docker-compose -f ./infra/docker-compose.yaml pull
      - uses: docker/build-push-action@v5.3.0
        with:
          context: .
          #cache-from: type=gha
          #cache-to: type=gha, mode=max


  
