name: Docker Compose Actions Workflow

on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - run: docker-compose -f ./infra/docker-compose.yaml pull
      
      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: docker-cache-{hash}

      - name: Build the stack
        id: build
        run: docker-compose -f ./infra/docker-compose.yaml build --progress=plain


  
