name: Docker Compose Actions Workflow

on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build the stack
        run: |
          mkdir -p /tmp/.docker-cache
          docker-compose -f ./infra/docker-compose.yaml build --progress=plain --build-arg BUILDKIT_INLINE_CACHE=1

      - name: Save Docker cache
        if: success()
        run: |
          docker save $(docker images --format '{{.Repository}}:{{.Tag}}' | grep -v '<none>') -o /tmp/.docker-cache/cache.tar
