name: Docker Compose Actions Workflow

on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the stack
        id: build
        run: |
          mkdir -p /tmp/.docker-cache
          docker-compose -f ./infra/docker-compose.yaml build --progress=plain
      - name: api test bruno
        run: |
          docker compose -f ./infra/docker-compose.yaml up --detach --wait
          npm install -g @usebruno/cli
          bru --version
          cd ./backend/test/hiveDriveAPI/
          bru run --insecure
          cd ../../../
          docker compose -f ./infra/docker-compose.yaml down
      - name: image api test curl and bruno
        run: |
          docker compose -f ./infra/docker-compose.yaml up --detach --wait
          npm install -g @usebruno/cli
          ./backend/test/image-test.sh
          docker compose -f ./infra/docker-compose.yaml down
          
      - name: integration test backend-keycloak
        run: |
          docker compose -f ./infra/docker-compose.yaml up --detach --wait
          ./backend/test/oauth-integration.sh
          ./backend/test/sql-integration.sh
          ./backend/test/add-stations.sh
          ./backend/test/add-vehicleCategories.sh
          docker compose -f ./infra/docker-compose.yaml down

