name: Docker Compose Actions Workflow

on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build and start Docker Compose services
        run: docker-compose -f ./infra/docker-compose.yaml up -d
  
      - name: Display Docker Compose service status
        if: always()
        run: docker-compose -f ./infra/docker-compose.yaml ps

      - name: List and Inspect Docker Containers
        if: always()
        run: |
          docker inspect --format='{{json .State.Health}}' infra_keycloak_1

      - name: Build the stack
        id: build
        run: |
          mkdir -p /tmp/.docker-cache
          docker-compose -f ./infra/docker-compose.yaml build --progress=plain
      - name: integration test backend-keycloak
        run: |
          docker compose -f ./infra/docker-compose.yaml up --detach --wait
          ./backend/test/oauth-integration.sh
          ./backend/test/sql-integration.sh
          ./backend/test/add-stations.sh
          docker compose -f ./infra/docker-compose.yaml down

          - name: Display Docker Compose service status
          run: docker-compose ps
    
    